Switch GNOME modules to GitHub.com.
gitlab.gnome.org sometimes fails with an error:

$  git clone --depth=1 --no-single-branch https://gitlab.gnome.org/GNOME/gtk.git gtk4 --branch 4.15.6
Cloning into 'gtk4'...
remote: Enumerating objects: 202975, done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
error: 11 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Switch to GitHub, to avoid that problem.